### ISSUE TITLE
node-gyp installation failure @ node >=0.11

### ISSUE THREAD

**Issue by tx44** [thegregorator/ttembed-js#1]
Please update deps for node-fs-ext. Installation is failing with node v0.11 and higher. Working node-fs-ext dependency e.g. is the latest v0.4.3.

https://github.com/baudehlo/node-fs-ext/issues/33
https://github.com/baudehlo/node-fs-ext/pull/37

**Comment by thegregorator** [comment]
Pushed a fix. Thanks for catching this!
